"use client";
import { useEffect, useState } from "react";
import { motion } from "framer-motion";
type Props={onComplete:(mode?:"desktop"|"recruiter"|"recovery")=>void};
const logs=["Initializing AMS-sec kernel...","Loading cybersecurity modules...","Mounting operator filesystem...","Loading professional profile...","Initializing security lab...","Mounting project repository...","Loading GreCyberSec operations...","Starting graphical environment..."];
export function Boot({onComplete}:Props){const [grub,setGrub]=useState(true),[sel,setSel]=useState(0),[shown,setShown]=useState(0),[ready,setReady]=useState(false); const options:[string,"desktop"|"recruiter"|"recovery"][]=[["AMS-sec OS","desktop"],["Recruiter Mode","recruiter"],["Recovery Mode","recovery"]];
 useEffect(()=>{const k=(e:KeyboardEvent)=>{if(grub){if(e.key==="ArrowDown")setSel(s=>(s+1)%options.length);if(e.key==="ArrowUp")setSel(s=>(s+options.length-1)%options.length);if(e.key==="Enter")setGrub(false)}else if(e.key==="Enter"&&ready)onComplete(options[sel][1]);};window.addEventListener("keydown",k);return()=>window.removeEventListener("keydown",k)},[grub,ready,onComplete,sel,options.length]);
 useEffect(()=>{if(grub)return; if(shown<logs.length){const t=setTimeout(()=>setShown(s=>s+1),240+Math.random()*220);return()=>clearTimeout(t)} const t=setTimeout(()=>setReady(true),450);return()=>clearTimeout(t)},[grub,shown]);
 if(grub)return <main className="boot"><div className="grub"><p>GNU GRUB &nbsp; AMS-sec OS</p>{options.map(([name],i)=><button key={name} onClick={()=>{setSel(i);setGrub(false)}} className={i===sel?"selected":""}>{i===sel?"* ":"  "}{name}</button>)}<small>Use ↑ ↓ and ENTER, or select an environment.</small><button className="skip" onClick={()=>onComplete("desktop")}>Skip Boot</button></div></main>;
 return <main className="boot"><div className="bootlog"><div className="bootbrand" aria-label="AMS-sec OS"><svg viewBox="0 0 74 74" aria-hidden="true"><path d="M37 4 64 18v22L37 69 10 40V18L37 4Z"/><path d="m22 39 10-17 5 10 6-10 10 17-8 12H30l-8-12Z"/></svg><div><h1>AMS-sec <span>Secure Boot v1.0</span></h1><small>ORIGINAL AMSSEC OS BOOT EMBLEM</small></div></div>{logs.slice(0,shown).map(l=><p key={l}><b>[ OK ]</b> {l}</p>)}{ready&&<motion.div initial={{opacity:0}} animate={{opacity:1}} className="bootready"><h2>AMS-sec OS</h2><p>Operator: Mohammed Almas Akkalath<br/>Environment: Cybersecurity &amp; Digital Forensics</p><button onClick={()=>onComplete(options[sel][1])}>Press ENTER to continue</button></motion.div>}</div><button className="skip" onClick={()=>onComplete("desktop")}>Skip Boot</button></main>}

