"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
import { filesystem, flatten, resolvePath, VFile } from "@/data/filesystem";
import {profile,projects,experience,certifications,skillGroups} from "@/data/portfolio";
type Props={openApp:(id:string)=>void}; type Line={input?:string;output?:string};
function pathStr(p:string[]){return "/home/almas"+(p.length?"/"+p.join("/"):"")};
function list(n:VFile|undefined){return n?.children?.map(x=>x.name+(x.type==="folder"?"/":"")).join("  ")||""}
export function Terminal({openApp}:Props){const [cwd,setCwd]=useState<string[]>([]),[lines,setLines]=useState<Line[]>([{output:"Welcome to AMS-sec OS. Type 'help' to inspect available commands."}]),[value,setValue]=useState(""),[history,setHistory]=useState<string[]>([]),[hi,setHi]=useState(-1);const input=useRef<HTMLInputElement>(null);const bottom=useRef<HTMLDivElement>(null);useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"});},[lines]);
 const run=(raw:string)=>{const cmd=raw.trim();let out="";const [head,...args]=cmd.split(/\s+/);const arg=args.join(" ");const node=resolvePath(cwd);if(!cmd)return;setHistory(h=>[...h,cmd]);setHi(-1);
 if(head==="help")out="help ls cd pwd cat tree clear whoami uname history echo date find grep open neofetch skills projects experience education certifications contact society research github linkedin cv";
 else if(head==="ls")out=list(node); else if(head==="pwd")out=pathStr(cwd); else if(head==="whoami")out="almas — cybersecurity & digital forensics operator"; else if(head==="uname")out="AMS-sec OS 1.0.0 browser-x86_64";else if(head==="date")out=new Date().toString();else if(head==="echo")out=arg;else if(head==="clear"){setLines([]);setValue("");return}
 else if(head==="history")out=history.map((h,i)=>`${i+1}  ${h}`).join("\n");else if(head==="cd"){if(!arg||arg==="~")setCwd([]);else if(arg==="..")setCwd(p=>p.slice(0,-1));else {const dest=arg.startsWith("/")?arg.replace("/home/almas","").split("/").filter(Boolean):[...cwd,arg];const f=resolvePath(dest);if(f?.type==="folder")setCwd(dest);else out=`cd: ${arg}: No such directory`;}}
 else if(head==="cat"){const dest=arg.startsWith("/")?arg.replace("/home/almas/","").split("/"):[...cwd,arg];const f=resolvePath(dest);out=f?.content??`cat: ${arg}: No such file`;}
 else if(head==="tree")out=flatten(filesystem).map(({path,file})=>`${"  ".repeat(path.split("/").length-3)}${file.type==="folder"?"▸ ":"· "}${file.name}`).join("\n");
 else if(head==="find")out=flatten(filesystem).filter(x=>x.file.name.toLowerCase().includes(arg.toLowerCase())).map(x=>x.path).join("\n")||"No matches.";
 else if(head==="grep")out="grep searches the AMS-sec virtual filesystem. Try: find project";
 else if(head==="open"){const found=flatten(filesystem).find(x=>x.file.name===arg||x.file.name.replace(/\..*/,"")===arg);if(found?.file.app){openApp(found.file.app);out=`Opening ${found.file.name}...`}else out=`open: ${arg}: not found`;}
 else if(head==="neofetch")out=`     █████╗ ███╗   ███╗ ███████╗\n    ██╔══██╗████╗ ████║ ██╔════╝     almas@amssec\n    ███████║██╔████╔██║ ███████╗     ─────────────────────\n    ██╔══██║██║╚██╔╝██║ ╚════██║     OS: AMS-sec OS\n    ██║  ██║██║ ╚═╝ ██║ ███████║     Host: University of Greenwich\n    ╚═╝  ╚═╝╚═╝     ╚═╝ ╚══════╝     Role: Cybersecurity Student\n                                      Certification: ISC² CC\n                                      Shell: amssec-shell`;
 else if(head==="skills"){openApp("skills");out="Opening evidence-based skills inventory..."}else if(head==="projects"){openApp("projects");out=`${projects.length} case files mounted.`}else if(head==="experience"){openApp("experience");out=`${experience.length} operation records available.`}else if(head==="education"){openApp("education");out=`${profile.university}\n${profile.degree}`}else if(head==="certifications"){openApp("certifications");out=certifications.join("\n")}else if(head==="contact"){openApp("contact");out=`Secure contact channel: ${profile.email}`}else if(head==="society"){openApp("grecybersec");out="GreCyberSec command center opening..."}else if(head==="research"){openApp("research");out="Research workspace opening..."}else if(head==="github"){window.open(profile.github,"_blank");out="Opening GitHub..."}else if(head==="linkedin"){window.open(profile.linkedin,"_blank");out="Opening LinkedIn..."}else if(head==="cv"){openApp("cv");out="Checking documents..."}else if(cmd==="sudo hire almas"){out="Evaluating candidate...\n\nCybersecurity ............ PASS\nTechnical projects ....... PASS\nLeadership ............... PASS\nCuriosity ................ PASS\n\nOpening secure contact channel...";openApp("contact")}else if(cmd==="sudo su")out="Permission denied.\n\nAMS-sec enforces least privilege.";else if(cmd==="rm -rf /")out="Operation blocked by AMS-sec Endpoint Protection.\nThreat prevented. Incident logged as AMS-0001.";else if(cmd==="nmap almas")out="Starting AMS-sec Nmap simulation...\n\nPORT      STATE    SERVICE\n22/tcp    open     cybersecurity\n80/tcp    open     portfolio\n443/tcp   open     cloud-security\n1337/tcp  open     ctf-labs\n8080/tcp  open     digital-forensics\n\n5 services discovered.";else if(cmd==="ping recruiter")out="PING recruiter.amssec [READY]: career connection established.";else if(cmd==="fortune")out="Security through curiosity. Build. Break. Understand. Improve.";else if(cmd==="cat /etc/motd")out="Welcome to AMS-sec OS.\n\nSecurity through curiosity.\nBuild. Break. Understand. Improve.";else out=`amssec-shell: ${head}: command not found`;
 setLines(l=>[...l,{input:`almas@amssec:${cwd.length?"~/"+cwd.join("/"):"~"}$ ${cmd}`,output:out}]);setValue("")};
 const submit=(e:FormEvent)=>{e.preventDefault();run(value)};return <div className="terminal" onClick={()=>input.current?.focus()}>{lines.map((l,i)=><div key={i}>{l.input&&<div className="prompt">{l.input}</div>}{l.output&&<pre>{l.output}</pre>}</div>)}<form onSubmit={submit}><span>almas@amssec:{cwd.length?"~/"+cwd.join("/"):"~"}$</span><input ref={input} aria-label="Terminal command" autoFocus value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>{if(e.key==="ArrowUp"){e.preventDefault();const n=Math.max(0,hi-1<0?history.length-1:hi-1);setHi(n);setValue(history[n]||"")}if(e.key==="ArrowDown"){e.preventDefault();const n=Math.min(history.length,hi+1);setHi(n);setValue(history[n]||"")}}}/></form><div ref={bottom}/></div>}

